### ISSUE TITLE
Both  listLeaderboardRecords and listLeaderboardRecordsAroundOwner Functions can't return full list.  even if ownerIds is null

### ISSUE THREAD

**Issue by okworld26** [heroiclabs/nakama-dart#52]
For example:

listLeaderboardRecords function,

If ownerId parameter is set to exact user id list,  It 's ok to return  the correct records.

But if ownerId is null or [], or just remove this parameter,   It return empty leaderboard records!

**Comment by okworld26** [comment]
According to Doc :https://heroiclabs.com/docs/nakama/client-libraries/javascript/#listing-the-top-records

empty ownerIds should return FULL record list.

**Comment by obrunsmann** [comment]
Hey, please use the provides issue template and add the installed package version as well as the flutter doctor output to your report.

**Comment by okworld26** [comment]
sorry,  version is 1.0.0-dev2.     Let me give more details soon

**Comment by okworld26** [comment]
**Describe the bug**

listLeaderboardRecords function,

If ownerId parameter is set to exact user id list, It 's ok to return the correct records.

But if ownerId is null or [], or just remove this parameter, It return empty leaderboard records!

**Reproduction Code**
        final allrecords = await nakamaClient!.listLeaderboardRecordsAroundOwner(
            session: session!,
            leaderboardName: globalLeaderBoardId,
          ownerId: null
            );

        print(oldrecord);  // this is empty records!,   it should be the full record list



**Expected behavior**

allrecords should return the full list of leaderboard record.  But it returns empty records.

output: flutter: LeaderboardRecordList(records: [], ownerRecords: [], nextCursor: , prevCursor: )

**Screenshots**
 

 
**pubspec.yaml**

[```yaml
(nakama: ^1.0.0-dev.2)
```]

**Additional context**
 
The leader board record has two records in fact.  But it retures empty records

**Comment by okworld26** [comment]
@obrunsmann ， hi.  any update on this?
Should I use raw http request to get the correct data as a workaround for now?

**Comment by obrunsmann** [comment]
> @obrunsmann ， hi. any update on this? Should I use raw http request to get the correct data as a workaround for now?

Currently tracking this issue with Nakama team. Coming back to you with some feedback soon :)

**Comment by iammuho** [comment]
No solution to that issue since 5 jan ?
