### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by Dragon863** [heroiclabs/nakama-dart#73]
Hi there! Thanks for the useful package, unfortunately I'm running into two issues. Firstly, the timestamps for the session expiry seem to be reported incorrectly (at some point in 1970), I believe this is because in `session.dart` `fromMillisecondsSinceEpoch` is being called on the decoded token which stores the token in *seconds* since epoch. Whilst this can be worked around by changing the arguments to `(token['exp'] as int) * 1000` in every line where this function is called in the file, I am still getting the message "Auth token invalid" when using any function with the session object (for example addFriends). I'm not sure if this is an issue with the package or the server I'm running, but I thought it could be relevant or maybe caused by the first issue.

I used the official docs and logged using email and then attempted to add a friend to the account using the following:
```dart
session = await client.authenticateEmail(
    username: "example",
    password: "example",
);
print(session.expiresAt);
await client.addFriends(
    usernames: ["test"],
    session: session,
);
```
This gives the following output:
```
flutter: 1970-01-20 15:29:28.873
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: gRPC Error (code: 16, codeName: UNAUTHENTICATED, message: Auth token invalid, details: [], rawResponse: null, trailers: {})
```
After applying the fix I mentioned above the session is reported as expiring at the correct date, but the second error still occurs.

I am using flutter 3.13.0 and the latest version of this ibrary on pub.dev, and the latest docker image of nakama. Thank you in advance!

**Comment by obrunsmann** [comment]
Thank you @Dragon863 for reporting. I am just back from vacation and checking in your issue shortly.

**Comment by LucaJeevanjee** [comment]
Hi I am getting the same! Auth token always invalid. Any progress?

**Comment by taciomedeiros** [comment]
This error is occuring because there is  no token sended by the client. There is an options parameter in the methods that make GRPC calls and a method to prepare session as token

![Captura de Tela 2023-11-12 às 09 03 38](https://github.com/heroiclabs/nakama-dart/assets/5381694/c66cdcbf-c0e7-4f36-9c65-86776489f947)

**Comment by ilmalte** [comment]
Bump :)

**Comment by obrunsmann** [comment]
Token parsing issue and missing options fixed in next release (releasing today)
