### ISSUE TITLE
After send data in socket method dart stops executing next method lines

### ISSUE THREAD

**Issue by taciomedeiros** [heroiclabs/nakama-dart#77]
**Describe the bug**
After send data to socket systems stop executing method lines without throws any error

**Reproduction Code**

Example:
```dart
Future<void> sendData() async {

 print('befor send data');
    await socket!.sendMatchData(
      matchId: match.matchId,
      opCode: Int64(data.opCode),
      data: jsonEncode({}).codeUnits,
    );

    print("after send data");
```

**Expected behavior**
 print("after send data"); should be called

**Screenshots**
<img width="978" alt="Captura de Tela 2023-11-19 às 14 30 18" src="https://github.com/heroiclabs/nakama-dart/assets/5381694/8da355d1-c058-4f94-ba62-31e14963267b">

**Flutter Doctor**

**pubspec.yaml**

**Additional context**

**Comment by obrunsmann** [comment]
There is no data returned from sendMatchData - so changed return type to void. Thanks for reporting.
