### ISSUE TITLE
Name filter doesn't work in ListGroups method

### ISSUE THREAD

**Issue by ilmalte** [heroiclabs/nakama-dart#83]
**Describe the bug**
If I pass only the parameters _session_ and _name_ to the listGroups method, the backend throws an exception saying:
`GrpcError (gRPC Error (code: 3, codeName: INVALID_ARGUMENT, message: name filter cannot be combined with any other filter, details: [], rawResponse: null, trailers: {}))`

**Reproduction Code**
Example:
```dart
 var listGroups = await NakamaClient.instance!.listGroups(
        session: session,
        name: "everyone",
      );
```

**Expected behavior**
I expect to retrieve a list of groups, filtered based on the name passed as filter.

**Additional context**
Considering the error message, it seems like only the name should be passed as filter and cannot be combined.
By using the API explorer through the console interface of Nakama, the endpoint works fine when the name only is passed (and the others are null).
I expect this issue to be in both client files: `nakama_grpc_client.dart` and `nakama_api_client.dart`
```dart
  @override
  Future<model.GroupList> listGroups({
    required model.Session session,
    String? name,
    String? cursor,
    String? langTag,
    int? members,
    bool? open,
    int limit = defaultLimit,
  }) async {
   final res = await _client.listGroups(
      api.ListGroupsRequest(
        name: name,
        cursor: cursor,
        langTag: langTag,
        limit: api.Int32Value(value: limit),
        members: api.Int32Value(value: members),
        open: api.BoolValue(value: open),
      );
      options: _getSessionCallOptions(session),
    );

    return model.GroupList.fromDto(res);
  }
```

I also tried to manually pass _null_ to all the parameters but in the name and I confirm this is the behavior the backend expects.

**Comment by zhangyc** [comment]
It seems that this library still cannot run stably.
