### ISSUE TITLE
ChannelMessage in models is not exported

### ISSUE THREAD

**Issue by zhangyc** [heroiclabs/nakama-dart#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangyc** [comment]
Maybe it would be better if I submit a PR

**Comment by obrunsmann** [comment]
Sure, always happy to. There are a large number of end points and parameters. I'm sure there are more points that I've overlooked.
Pleas describe the model in this case, I can easily add the data and extend our test cases then.

**Comment by obrunsmann** [comment]
Merged
