### ISSUE TITLE
List User Groups doesn't return the groups users are member but just superadmin

### ISSUE THREAD

**Issue by iammuho** [heroiclabs/nakama-dart#89]
**Describe the bug**
I;m trying to call the groups, users are member of (but not superadmin) and this function doesn't return any data.

```dart
 await client.listUserGroups(
                session: getIt<NakamaClient>().session,
                userId: getIt<NakamaClient>().session.userId,
              );
```

If I don't set the userID, it throws `GrpcError(code: 3, message: User ID must be set.)
flutter: GrpcError(code: 3, message: User ID must be set.)`

If the user is the superadmin, all works.

How can I solve that issue ? I

**Comment by obrunsmann** [comment]
@iammuho fixed from 1.0.6. Please check with the version once it's released
